name: FanBattle
main: Xoosted\Plugin
version: 1.0.0
api: [2.0.0, 3.0.0-ALPHA12]
author: Xoosted
#commands:
#fbhelp:
#description: "shows all commands for fan battle"
#usage: "/fb help"
#permission: "fb.command"

 #fbinfo:
 #description: "shows more information about the plugin"
 #usage: "/fb info"
 #permission: "fb.command.info"
 
 #fbstart:
 #description: "Allows you to start a fan battle"
 #usage: "/fb start"
 #permission: "fb.srt.command"
 
 #fbjoin:
 #description: "Allows you to join an active Fan Battle event."
 #usage: "/fb join"
 #permission: "fb.command.join"
 
 #fbleave:
 #description: "Allows you to leave an active Fab Battle event."
 #usage: "/fb leave"
 #permission: "fb.command.leave"
