name: FanBattle
main: Xoosted\Plugin
version: 1.0.0
api: [2.0.0, 3.0.0-ALPHA12]
author: Xoosted
#commands:
 #cw:
  #description: "executes and starts a fan war"
  #usage: "/cw"
  #permission: "cw.command"
